# Generated by Django 3.2.9 on 2021-12-02 14:17

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oursite', '0005_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, verbose_name='Видео'),
        ),
    ]
