# Generated by Django 3.2.9 on 2021-12-02 14:53

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oursite', '0008_auto_20211202_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='title',
        ),
        migrations.AlterField(
            model_name='item',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, verbose_name='Видео'),
        ),
    ]
