# Generated by Django 3.2.9 on 2021-12-02 14:59

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oursite', '0009_auto_20211202_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='video',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
