# Generated by Django 3.2.9 on 2021-12-02 15:10

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oursite', '0010_alter_item_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='vid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_Title', models.CharField(max_length=200)),
                ('vid_Body', models.TextField()),
                ('vid_Video', embed_video.fields.EmbedVideoField()),
            ],
            options={
                'verbose_name_plural': 'Vid',
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
