# Generated by Django 3.2.9 on 2021-12-07 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oursite', '0011_auto_20211202_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='vid',
            name='vid_Image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
    ]
