# Generated by Django 3.2.9 on 2021-12-07 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oursite', '0012_vid_vid_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vid',
            name='vid_Course',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
