# Generated by Django 3.2.9 on 2021-12-07 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oursite', '0013_vid_vid_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='vid',
            name='vid_Media',
            field=models.FileField(default=django.utils.timezone.now, upload_to='video/%y'),
            preserve_default=False,
        ),
    ]
