# Generated by Django 3.2.9 on 2021-12-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oursite', '0014_vid_vid_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vid',
            name='vid_Media',
            field=models.FileField(upload_to='media/%y'),
        ),
    ]
