# Generated by Django 3.2.9 on 2021-12-07 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oursite', '0019_alter_vid_vid_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vid',
            name='vid_Video',
        ),
    ]
