# Generated by Django 3.2.9 on 2021-12-08 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oursite', '0020_remove_vid_vid_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vid',
            new_name='Vidos',
        ),
        migrations.AlterModelOptions(
            name='vidos',
            options={},
        ),
    ]
