# Generated by Django 3.2.9 on 2021-12-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oursite', '0021_auto_20211209_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='video/')),
            ],
        ),
        migrations.DeleteModel(
            name='Vidos',
        ),
    ]
