# Generated by Django 3.2.9 on 2021-12-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oursite', '0022_auto_20211209_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='preview',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
