# Generated by Django 3.2.9 on 2021-12-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oursite', '0024_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='preview',
            field=models.ImageField(upload_to=''),
        ),
    ]
