# Generated by Django 3.2.9 on 2021-12-13 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oursite', '0026_alter_video_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
