# Generated by Django 3.2.9 on 2021-12-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oursite', '0027_video_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='preview',
            field=models.FileField(upload_to='media/'),
        ),
    ]
