# Generated by Django 3.2.9 on 2021-12-14 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oursite', '0029_alter_video_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='video',
            field=models.FileField(default=django.utils.timezone.now, upload_to='video/'),
            preserve_default=False,
        ),
    ]
